name: NekoAnticheat
version: 1.0
main: neko.anticheat.Anticheat
api-version: 1.21
softdepend: [Citizens]

commands:
  nac:
    description: 配置重载
    usage: /nac reload 或
  dummy:
    description: 创建假人
    usage: /nac dummy <玩家名>